### ISSUE TITLE
unknown type name 'ofPoint' with oF 0.9.8

### ISSUE THREAD

**Issue by transat** [danomatika/ofxAppUtils#10]
I'm getting at least two errors when trying to compile a new project with ofxAppUtils and the latest openFrameworks (0.9.8):

in ofxParticle.h:

`ofxParticle(ofPoint pos, float w, float h);`

yields _unknown type name 'ofPoint'._

Also getting the same error for this line in ofxParticle.cpp:

`ofxParticle::ofxParticle(ofPoint pos, float w, float h) : `

I've defined the OF_USE_LEGACY_MESH constant in ofConstants.h, if that helps.

**Comment by transat** [comment]
Using `glm::vec3` instead of `ofPoint` seems to have fixed it.

**Comment by danomatika** [comment]
>latest openFrameworks (0.9.8)

This add-on is tested against the latest stable *release*, not the current development version, which is what you are using aka not what I would consider "0.9.8".

It looks like an issue with the typedef of the ofPoint class and not something necessarily wrong with ofxAppUtils use of it. I would open an issue on the openFrameworks project.

**Comment by transat** [comment]
Ok cheers. Will do.

**Comment by transat** [comment]
A simple fix! Arturo says...

> it seems you are just not including the header that defines ofPoint. in ofxParticle.h it includes ofxTimer.h and ofRectangle.h if you also include ofPoint.h it should work. it worked before cause ofRectangle used ofPoint so it was included indirectly through ofRectangle but now ofRectangle uses glm::vec3 instead.
> 
> just add:
> `#include "ofPoint.h"`
> after the other includes in ofxParticle.h and it should work
