### ISSUE TITLE
Quad warp a Video

### ISSUE THREAD

**Issue by martialgallorini** [danomatika/ofxAppUtils#8]
Hello 

Is there a way to use quad warp with a video ?

thanks a lot

**Comment by danomatika** [comment]
The quad warper just applies a set of GL transforms to whatever is between it's push() & pop() methods, so it can warp pretty much anything. A video is draw onto a text and will warp just fine. Why not try it?

**Comment by martialgallorini** [comment]
Ok thanks for the information.

I think i don't really get how it works yet but i will give it a try.

thanks a lot

**Comment by danomatika** [comment]
This is where the code comes from, see the included videos: https://forum.openframeworks.cc/t/quad-warping-an-entire-opengl-view-solved/509/12

**Comment by martialgallorini** [comment]
ok thanks. i will figure out how to use it.
thanks a gain
